---
members:
  type: array
  items:
    type: string
  description: "List team members"
assignments:
  type: array
  items:
    type: string
  description: "List of patching assignments"
pins:
  type: object
  description: "Used to pin a member(s) to an assignment. e.g. {'member': 'assignment'}"
  required: false
  additionalProperties: true
